version: "3.8"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/work
      - vendor-store:/work/vendor

  web:
    build: ./infra/nginx
    ports:
      - 80:80
      - 443:443
      - 3000:3000
      - 3001:3001
    volumes:
      - ./backend:/work
      - node_modules-store:/work/node_modules
    working_dir: /work
    depends_on:
      - app

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=translation
      - MYSQL_USER=phper
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - TZ=Asia/Tokyo

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=secret
    links:
      - db
    ports:
      - 8080:80
    volumes:
      - /sessions

volumes:
  db-store:
  node_modules-store:
  vendor-store: